Models/ErrorViewModel.cs
namespace COMP003B.Assignment4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/OrderModel.cs
using System.ComponentModel.DataAnnotations;

namespace COMP003B.Assignment4.Models
{
    public class Order
    {
        [Required(ErrorMessage = "Book title is required.")]
        [MinLength(10, ErrorMessage = "Book title length needs to be more than 10 characters.")]
        public string BookTitle { get; set; }

        [Required(ErrorMessage = "Amount is required.")]
        [Range (1, 100, ErrorMessage = "Too many or less than one book.")]
        public int Amount { get; set; }

        [Required(ErrorMessage = "Addressis required.")]
        [MinLength(3, ErrorMessage = "Address too short.")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email address format.")]
        public string Email { get; set; }
    }
}

Models/Rulebook.cs
using System.ComponentModel.DataAnnotations;

namespace COMP003B.Assignment4.Models
{
    public class Rulebook
    {
        [Required]
        [MinLength(10)]
        public string Title { get; set; }

        [Required]
        [Range(1, 10)]
        public int Edition { get; set; }

        [Required]
        [Range(1990, 2030)]
        public int Publication { get; set; }

        [Required]
        [Range(50, 1000)]
        public int PageNumbers { get; set; }
    }
}

Controllers/CthulhuController.cs
using COMP003B.Assignment4.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment4.Controllers
{
    [Route("/call-of-cthulhu")]
    public class CthulhuController : Controller
    {
        //GET /call-of-cthulhu
        //Displays the gamespecs page
        [HttpGet]
        [Route("")]
        public IActionResult GameSpecs()
        {
            ViewData["Title"] = "Call of Cthulhu - Specifications";
            return View();
        }

        //POST /call-of-cthulhu/subscribe
        //This adds a form to "subscribe" to a sort of newletter
        [HttpPost]
        [Route("subscribe")]
        public IActionResult Subscribe(string email)
        {
            if (string.IsNullOrEmpty(email))
            {
                ModelState.AddModelError("", "Email is required");
                return RedirectToAction("GameSpecs");
            }

            //This is purely cosmetic because we don't really have a database connected to this
            return RedirectToAction("GameSpecs", new { subscribed = true });
        }

        //GET /productlist
        //Displays the productlist page
        //This is where the rulebook model goes
        [HttpGet]
        [Route("/productlist")]
        public IActionResult ProductList()
        {
            List<Rulebook> rulebooks = new()
            {
                new Rulebook
                {
                    Title = "Call of Cthulhu Keeper Rulebook",
                    Edition = 7,
                    Publication = 2023,
                    PageNumbers = 200
                },
                new Rulebook
                {
                    Title = "Pulp Cthulhu",
                    Edition = 7,
                    Publication = 2020,
                    PageNumbers = 300
                },
                new Rulebook
                {
                    Title = "Malleus Monstrorum",
                    Edition = 7,
                    Publication = 2021,
                    PageNumbers = 400
                }
            };
            return View(rulebooks);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using COMP003B.Assignment4.Models;
using Microsoft.AspNetCore.Mvc;

namespace COMP003B.Assignment4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OrderController.cs
using System.Diagnostics;
using COMP003B.Assignment4.Models;
using Microsoft.AspNetCore.Mvc;

Controllers/StoreController.cs
using COMP003B.Assignment4.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace COMP003B.Assignment4.Controllers
{
    public class StoreController : Controller
    {
        //sends user to order page
        [HttpGet]
        public IActionResult Order(int? id)
        {
            return View(new Order());
        }
        //logs the order details 
        [HttpPost]
        public IActionResult Order(Order order)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Title"] = "Invalid Order Form";
                return View(order);
            }

            return RedirectToAction("Success", new
            {
                BookTitle = order.BookTitle,
                Amount = order.Amount,
                Email = order.Email,
                Address = order.Address
            });
        }
        //sends user to success page

        [HttpGet]
        public IActionResult Success(string bookTitle, int amount, string email, string address)
        {
            var order = new Order
            {
                BookTitle = bookTitle,
                Amount = amount,
                Email = email,
                Address = address
            };            
            return View(order);
        }
    }
    

    /*
        [HttpGet]
        public IActionResult Success(string book)
        {
            ViewData["Title"] = "Purchase Confirmation";
            ViewData["Book"] = book;
            return View();
        }

        [HttpGet]
        public IActionResult Shipping()
        {
            ViewData["Title"] = "Shipping Information";
            ViewData["Policy"] = "We wont actually ship sorry </3";
            ViewData["Cost"] = "But it is free!";
            return View();
        }
    }
    */
}

Views/Cthulhu/GameSpecs.cshtml
@{
    ViewData["Title"] = "Call of Cthulhu - Specifications";
    Layout = "_Layout";
}

<div class="cthulhu-theme">
    <h1>@ViewData["Title"]</h1>

    <div class="game-specs">
        <h2>Core Mechanics</h2>
        <ul>
            <li>D100 system</li>
            <li>Sanity mechanics</li>
            <li>1920s setting</li>
        </ul>
    </div>

    <!-- Form to accses subscription page -->
    <form asp-action="Subscribe" method="post">
        <input type="email" name="email" placeholder="Email" required />
        <button type="submit">Subscribe to Newsletter</button>
    </form>
    <!--Thank you stack overflow people teaching me how to read values. Im sure there was a simplier way but whatever-->
    <!--https://stackoverflow.com/questions/41577376/how-to-read-values-from-the-querystring-with-asp-net-core#41577446--->
    @if (Context.Request.Query["subscribed"] == "True")
    {
        <div class="alert alert-success mt-3">Thank You!</div>
    }
</div>

Views/Cthulhu/ProductList.cshtml
@{
    ViewData["Title"] = "Call of Cthulhu - Product Listings";
    Layout = "_Layout";
}

<div class="cthulhu-theme">
    <h1>@ViewData["Title"]</h1>

    <!--Bootstrap isnt always the prettiest thing but I am glad i kept my old CSS repositories-->
    <!--Basicly this is a flexbox which "flexes" the items in grid to fit into the screen size. As I zoom in 2 columns become 1, so this may be useful for mobile use-->
    <div class="row row-cols-1 row-cols-md-2">
        <!---C# intregation with HTML is a game changer-->
        @foreach (var book in Model)
        {
            <div class="col">                
                <div class="card-body">
                    <h3><strong>@book.Title</strong></h3>
                    <h4><strong>Edition</strong> @book.Edition</h4>
                    <p class="card-text text-muted">
                        Published: @book.Publication
                        Page Count: @book.PageNumbers
                    </p>
                </div>              
            </div>
        }
    </div>
</div>

Views/Cthulhu/subscribe.cshtml
@{
    ViewData["Title"] = "Call of Cthulhu - Specifications";
    Layout = "_Layout";
}
<!--The subscribe page is the same as the gamespecs page aside from the different URL path -->
<div class="cthulhu-theme">
    <h1>@ViewData["Title"]</h1>

    <div class="game-specs">
        <h2>Core Mechanics</h2>
        <ul>
            <li>D100 system</li>
            <li>Sanity mechanics</li>
            <li>1920s setting</li>
        </ul>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Call of Cthulhu";
}

<div class="text-center">
    <h1 class="display-4">Welcome... To your doom</h1>
    <h3>Call of Cthulhu is a Table Top RPG created by Chaosium</h3>
    <p>Multiple players investiagate a mystery created by "The Keeper" who manages the game as a whole</p>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Call of Cthulhu TTRP Fan Site</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/COMP003B.Assignment4.styles.css" asp-append-version="true" />

    <style>
        body {
            /*this is about all the CSS I have time for*/
            background-color: #0a0a1a;
            color: #e0e0e0;
            font-family: 'Times New Roman', serif;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">COMP003B.Assignment4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cthulhu" asp-action="GameSpecs">What is Call of Cthulhu?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cthulhu" asp-action="ProductList">Rule Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Order">Purchase</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - COMP003B.Assignment4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_StoreNav.cshtml
<!--This code was re-used from COMP003B.Assignment3 I just changed the relavent figures from there to here->

<nav class="nav">
    <ul>
        <li class="nav-item">
            <a class="nav-link" href="/store/order">Store Page</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/call-of-cthulhu">Call of Cthulhu</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/productlist">Rulebooks</a>
        </li>
    </ul>
</nav>

Views/Store/Order.cshtml
@model COMP003B.Assignment4.Models.Order
@{
    ViewData["Title"] = "Call of Cthulhu - Book Orders";
    Layout = "_Layout";
}

<div class="cthulhu-theme"> <!--This is for CSS if I get the time to do it-->
    <h1>@ViewData["Title"]</h1>

    <partial name="_StoreNav" />

    <!--Code recycled from assignment 3-->
    <form asp-action="Order" method="post" asp-controller="Store">
        <div class="form-group">
            <label asp-for="BookTitle"></label>
            <input asp-for="BookTitle" class="form-control" />
            <span asp-validation-for="BookTitle" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Amount"></label>
            <input asp-for="Amount" class="form-control" />
            <span asp-validation-for="Amount" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" type="email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control"/>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Purchase</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Store/Success.cshtml
@model Order
@{
    ViewData["Title"] = "Your purchase was most successful";
    Layout = "_Layout";
}

<div class="cthulhu-theme">
    <h1>@ViewData["Title"]</h1>
    <partial name="_StoreNav" />
    <h2>The books will be delierved, and so will the horrors</h2>
    <!--The code below was taken from assignment3 just with all the needed bits taken out-->
    <ul>
        <li><strong>The book ordered is </strong> @Model.BookTitle</li>
        <li><strong>The ammount of have ordered is </strong> @Model.Amount</li>
        <li><strong>The email you have entered is Email: </strong> @Model.Email</li>
        <li><strong>The shipping address is </strong> @Model.Address</li>
    </ul>

</div>